### ISSUE TITLE
unequal forward/reverse scaling factors power-of-2 FFT

### ISSUE THREAD

**Issue by Phillip-Wang** [projectNe10/Ne10#101]
Currently, Ne10 always scales its output in reverse (backward) power-of-2 FFT, but not in forward counterpart.

**Comment by joesavage** [comment]
AFAIK, using a simple summation for the forwards transformation and then scaling by `1 / N` in the reverse transformation is a fairly common thing to do. We might want to support different scaling factors in future, so this is a reasonable feature request, but I don't think it's worth us considering at the moment. If we look at what other libraries do (considering only the C2C case for now):

- Apple's vDSP leaves the result completely unscaled in both directions (leaving any scaling up to the user).
- FFTW does the same thing we do.
- KissFFT does different things in their floating point FFTs to their fixed point ones to avoid overflow issues. Specifically, it looks like they're using unscaled results in the former case, and `1 / sqrt(N)` scaling in both directions in the latter.
- Some other libraries scale by `1 / N` in the forwards transformation and leave the inverse transformation as a simple summation.

So it doesn't look like there's any easy answer to what we should support here. My suggestion is that we continue with a standard scaling factor for now, and let users scale the results from this as they see fit.
