### ISSUE TITLE
Crash when freeing cfg created by ne10_fft_alloc_r2c_float32(Size);

### ISSUE THREAD

**Issue by Codewyvern** [projectNe10/Ne10#102]
I am compiling for the iOS arm architecture and getting a crash when calling free() or NE10_FREE on the cfg created with ne10_fft_r2c_cfg_float32_t Plan = ne10_fft_alloc_r2c_float32(Size);
However this version for c2c does not crash auto Plan = ne10_fft_alloc_c2c_float32_neon(Size);

What could be wrong? That's the only problem I have right now.

Edit: Forgot to mention it does not happen on Aarch64

**Comment by Phillip-Wang** [comment]
Please provide compile log, in plain text. It would help us to root the cause, if you also provide your steps to compile Ne10.

**Comment by Codewyvern** [comment]
Here is how I compiled the library (because I am using Marmalade SDK)

#ifdef I3D_ARCH_ARM
#include <arm/lib/gcc/arm-none-eabi/4.8.3/include/arm_neon.h>
#else
#include <aarch64/lib/gcc/aarch64-none-elf/4.9.2/include/arm_neon.h>
#endif

In types remove the headers that are not needed
In init comment out the function pointers that are not needed

There will be 3 functions that are duplicates, so in the intrinsic files wrap a single function with:

#ifndef I3D_ARCH_ARM
#endif

And on the normal version this:

#ifdef I3D_ARCH_ARM
#endif

Comment out scaling defines and set is_backward_scaled = 0

And the compile log, I will send you it by email.
