### ISSUE TITLE
Major slowdown introduced by math module functions

### ISSUE THREAD

**Issue by jmaximoff** [projectNe10/Ne10#106]
Hi,

I have a Linux ARMv7 application that requires a real-to-real FFT for an input vector of size 128. I typically implement this using a real-to-complex FFT and then compute the entry-by-entry squared-magnitude (re[j]^2 + im[j]^2). I've seen huge performance improvements moving from FFTW to Ne10 for the real-to-complex FFT (thanks!), but when I attempt to use Ne10 math functions to compute the squared-magnitudes from the FFT's complex output vector, most of my performance gains are lost. I wonder if I am doing something wrong in the vectorized magnitude computation. Here is my basic process:

0. Pre-allocate 4 buffers (tmpRe, tmpIm, tmpRe2, tmpIm2) to allow the out-of-place computations.

1. Load tmpRe and tmpIm with the real and imaginary components of the FFT output buffer in a for-loop. (I don't need to do this when I use FFTW as FFTW output can be individually addressed for the real vector and the imaginary vector... maybe this additional for-loop is the entire source of the performance hit that I see???).

2. ne10_mul_float_neon(tmpRe2, tmpRe, tmpRe, 128);

3. ne10_mul_float_neon(tmpIm2, tmpIm, tmpIm, 128); 

4. ne10_add_float_neon(tmpRe, tmpRe2, tmpIm2, 128);

The difference between doing the squared-magnitude calculation this way and using a naive entry-by-entry for-loop approach is a slowdown of approximately 20-25%. Of course, I can simply use the Ne10 FFT and revert to doing the magnitude computations in a loop, but I wanted to check first that I am not somehow misusing the Ne10 vector math functions.

Any help or advice would be appreciated. 

-Josh

**Comment by Phillip-Wang** [comment]
Hi @jmaximoff,

Since what you need is (re[j]^2 + im[j]^2), or dot ({re[j], im[j]}, {re[j], im[j]}), you can try [ne10_dot_vec2f_neon](https://github.com/projectNe10/Ne10/blob/master/inc/NE10_math.h).
In your case, output from Ne10's complex to real is like vec2[128+1] = { re0, 0.0, re1, im1, ..., re128, 0.0}. You can call ne10_dot_vec2f_neon (result_len, vec2, vec2, 128).

**Comment by jmaximoff** [comment]
Hi @Phillip-Wang,

Thanks for the quick reply! Your dot product idea is a good one, and avoids the buffer copy in my original implementation. It is an improvement, but still slightly slower (by less than 5%) than the naive loop-based approach, though.

To be clear, by naive loop-based, I mean:
for(int j = 0; j < 128; ++j){
     int k = some_reindexing_function(j);
     output[k] = freq_gain[j] * (complex[j].r * complex[j].r + complex[j].i * complex[j].i);
}

which I replaced with
ne10_dot_vec2f_neon(tmpRe, (ne10_vec2f_t*)complex, (ne10_vec2f_t*)complex, 128);
ne10_mul_float_neon(tmpRe2, tmpRe, freq_gain, 128);
for(int j = 0; j < 128; j++){
    int k = some_reindexing_function(j);
    output[k] = tmpRe2[j];
}

Unfortunately, the reindexing is necessary, so I can't eliminate all loops in the Ne10 implementation. 

For reference, I'm using Linaro-2014.04 (GCC 4.8) with a command line:
arm-linux-gnueabihf-g++ -c -pipe -Wno-psabi -mfpu=neon -mfloat-abi=hard -mtune=cortex-a8 -fPIC -O2 -ffunction-sections -fdata-sections -fvisibility=hidden -fvisibility-inlines-hidden -D_REENTRANT -Wall -W -std=c++98 -Wno-long-long -pedantic-errors -Werror -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -DUSE_NE10 -D_GNU_SOURCE -I../Ne10/inc

As I mentioned, it's not a big deal... I've already gotten a big win out of Ne10's fft implementation. Hopefully my notes provide a simple and helpful use-case for your team for the next development cycle.

Best,
Josh

**Comment by Phillip-Wang** [comment]
Hi @jmaximoff , could you provide details of the reindexing?
