### ISSUE TITLE
Build fails on iOS armv7

### ISSUE THREAD

**Issue by JonathanLennox** [projectNe10/Ne10#111]
When I build Ne10 for iOS armv7, I get the following error:

[ 49%] Building C object modules/CMakeFiles/NE10.dir/CMakeFiles/NE10.dir/NE10_fft_float32_ios.neon.s.o
/Users/jonathan/Cvs/FrameworkSources/Ne10/Ne10-git/build-armv7/modules/CMakeFiles/NE10.dir/NE10_fft_float32_ios.neon.s:181:1: error: invalid symbol redefinition
LPC0_0:
^
/var/folders/h5/c087y0n56654x6xyn9crr4d40nh10z/T/NE10_fft_float32_ios-85b0e1.s:476:9: note: while in macro instantiation
        BUTTERFLY8X2_WITHOUT_TWIDDLES "TRUE"
        ^
make[2]: *** [modules/CMakeFiles/NE10.dir/CMakeFiles/NE10.dir/NE10_fft_float32_ios.neon.s.o] Error 1

Ne10 git head, commit d1071c83f4ac8ed82b9fc0c2f284db8c6c0ff284 (Tue Apr 7 16:18:39 2015 +0800)

OS X 10.10.3
Xcode 6.3.1

Configured with
NE10_IOS_TARGET_ARCH=armv7 cmake -DCMAKE_TOOLCHAIN_FILE=../ios/ios_config.cmake ..

**Comment by Phillip-Wang** [comment]
Confirmed.

**Comment by fgao9310** [comment]
Replace 'LPC0_0' with a number string, such as '1'.

**Comment by Phillip-Wang** [comment]
Hi @fgao9310, did you mean replacing 'LPC0_0' fix this issue?

**Comment by ujamshy** [comment]
Hi, I get the same error.
Is there a fix to the problem?

**Comment by Phillip-Wang** [comment]
Hi ujamshy, there will be a patch soon.

**Comment by Phillip-Wang** [comment]
Hi @ujamshy and @JonathanLennox , if it is fixed, please kindly close this issue when convenient.

**Comment by ujamshy** [comment]
For me it is fixed. I do not know however how to close the issue. Thanks.
