### ISSUE TITLE
Build fails on iOS arm64

### ISSUE THREAD

**Issue by JonathanLennox** [projectNe10/Ne10#112]
When I build Ne10 for iOS arm64, linking fails with the following error:

Linking C executable NE10_dsp_unit_test_smoke
Undefined symbols for architecture arm64:
  "___cxa_guard_acquire", referenced from:
      void ne10_c2c_1d_last_stage_neon<true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<2, true, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<4, true, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<3, true, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<5, true, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<2, false, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<3, false, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      ...
  "___cxa_guard_release", referenced from:
      void ne10_c2c_1d_last_stage_neon<true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<2, true, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<4, true, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<3, true, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<5, true, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<2, false, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      void ne10_radix_butterfly_int32_neon<3, false, true, true>(int32x4x2_t*, int32x4x2_t const*, ne10_fft_cpx_int32_t const*, int, int, int) in libNE10.a(NE10_fft_generic_int32.neonintrinsic.cpp.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/NE10_dsp_unit_test_smoke] Error 1
make[1]: *** [test/CMakeFiles/NE10_dsp_unit_test_static.dir/all] Error 2
make: *** [all] Error 2

I'm guessing this is C++ code being linked with a C compiler?

Ne10 git head, commit d1071c83f4ac8ed82b9fc0c2f284db8c6c0ff284 (Tue Apr 7 16:18:39 2015 +0800)

OS X 10.10.3
Xcode 6.3.1

Configured with
NE10_IOS_TARGET_ARCH=arm64 cmake -DCMAKE_TOOLCHAIN_FILE=../ios/ios_config.cmake ..

**Comment by Phillip-Wang** [comment]
Hi @JonathanLennox, you are right. I will take care of it.
