### ISSUE TITLE
NE10 issue

### ISSUE THREAD

**Issue by RRRZZZVVV** [projectNe10/Ne10#114]
Hello all,

I tried to compile Ne10 on Linux, and I see this error:

-- Target architecture : 
CMake Error at CMakeLists.txt:83 (if):
  if given arguments:
    "STREQUAL" "armv7"
  Unknown arguments specified
-- Configuring incomplete, errors occurred!

Can anyone tell what is wrong?

Thx,
DD.

**Comment by Phillip-Wang** [comment]
How did you build it? Something like this?

```
makedir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=../GNUlinux_config.cmake ..
make -j16
```

I guess you have not specify CMAKE_TOOLCHAIN_FILE.

**Comment by RRRZZZVVV** [comment]
Hi Phillip, thanks for your quick answer,

That error has appeared when I did:  
 cmake -DCMAKE_TOOLCHAIN_FILE=../GNUlinux_config.cmake ..
So, I specified CMAKE_TOOLCHAIN_FILE.

Regards.

**Comment by Phillip-Wang** [comment]
@RRRZZZVVV ,
Well, how about ```export NE10_LINUX_TARGET_ARCH=armv7" before you run cmake? I assume you are building for ARM v7-A.

**Comment by RRRZZZVVV** [comment]
I have tried, but no succes.
Yes, I'm building for ARM v7-A.
Should I have installed other applications than gcc, g++, make, cmake? Maybe something is missing on my OS...

Regards.

**Comment by Phillip-Wang** [comment]
That is odd. Have you check the spelling? Last time I saw this error, it was because of a small typo.

**Comment by RRRZZZVVV** [comment]
Hi Phillip,

I have resolved this problem by adding this code at the beginning of CMakeLists.txt:

	add_definitions(-DNE10_LINUX_TARGET_ARCH)
        set(GNULINUX_PLATFORM true)
        set(NE10_TARGET_ARCH "armv7")

Maybe it's not the perfect way for solving this problem, but at least I manage to compile this library (both static and dynamic) and now I can use it.

Many thanks!

**Comment by Phillip-Wang** [comment]
I can not reproduce this issue on my environment, so I don't know why you have to add this code to get it compiled.
Thanks for your input.

**Comment by Ecordonnier** [comment]
I had the same error, the solution in my case was:

$ rm -rf * (in the build directory)
$ cmake -DCMAKE_TOOLCHAIN_FILE=../GNUlinux_config.cmake ..
(this time it works).
