### ISSUE TITLE
NE10 - using issues

### ISSUE THREAD

**Issue by RRRZZZVVV** [projectNe10/Ne10#116]
Hello all,

- I need some help on a problem: I have created NE10 library (ARM platform, static library). My OS: Ubuntu 14 LTS. The library has 299 kB.
- When I try to compile an example using NE10 library (with gcc-4.8 compiler), the compiler show me an error like this:

"skipping incompatible /MY_PATH/libNE10.a when searching for /MY_PATH/libNE10.a
/usr/bin/ld: cannot find /MY_PATH/libNE10.a
collect2: error: ld returned 1 exit status"

BUT:
When I try to compile the same example using "arm-linux-gnueabihf-g++-4.8" instead of "gcc-4.8" everything it's OK!

Compile command&example is this: $gcc –O2 -o sample sample.c  -I$NE10_INC_PATH -l:$NE10_LIB_PATH/libNE10.a   (from http://community.arm.com/groups/android-community/blog/2013/09/26/ne10-library-getting-started)

The problem is that my makefile is using "gcc-4.8" and I need to use this compiler.
I think it should work also with "gcc" as long as the example from official website is working with "gcc".

Does anyone know where is the problem?

Regards!

**Comment by Phillip-Wang** [comment]
Hi @RRRZZZVVV ,

I think that document is talking about native compile, so we use "gcc" there.
Are you cross compiling? If so, you should modify your makefile to use proper toolchain.

**Comment by RRRZZZVVV** [comment]
Hello Phillip,
Yes, I think you are right, I will modify my makefile. I'm compiling on Ubuntu for ARM processors. I thought that my Ne10 library is corrupt or it was't created correctly.

Thank you again!
