### ISSUE TITLE
Ne10 Speed problems

### ISSUE THREAD

**Issue by RRRZZZVVV** [projectNe10/Ne10#119]
Hello all,

- I would have one question related to Ne10 library: i try to use "ne10_dot_vec4f_neon" method from Ne10, but it seems that is very-very slow compared to a C implementation when it comes to calculate dot_product. It's about 50x slower. Is there a reason for this?

Regards!

**Comment by Phillip-Wang** [comment]
Hi @RRRZZZVVV ,
I wonder how many vectors you are dealing with. If you are computing dox product of a single vector which contains 4 elements, `ne10_dot_vec4f_neon` might not be the best choice.
However, 50x is a surprising result. What is the "C implementation" here?

**Comment by RRRZZZVVV** [comment]
Hi Phillip,
Sorry, it was a very stupid problem related to "printf" function which is not working properly in some cases and show wrong results. Now, as a matter of fact, in my case NE10 method was up to 25% faster than C implementation.

Thanks, and sorry again.
