### ISSUE TITLE
Can't get past cmake on Raspberry PI 2 with Debian Jessie

### ISSUE THREAD

**Issue by w4mmp** [projectNe10/Ne10#120]
HI,
NE10_LINUX_TARGET_ARCH=armv7

Receive this when attempting to run cmake:
cmake -DGNULINUX_PLATFORM=ON ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target architecture :
CMake Error at CMakeLists.txt:83 (if):
  if given arguments:

    "STREQUAL" "armv7"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/home/ron/src/Ne10/build/CMakeFiles/CMakeOutput.log".

Thanks.
Ron / W4MMP

**Comment by Phillip-Wang** [comment]
I am not sure why. Right now, please use following command:
`cmake -DGNULINUX_PLATFORM=ON -DNE10_LINUX_TARGET_ARCH=armv7 ..`

**Comment by w4mmp** [comment]
Hi,
Thank you.  Yes, that corrected the issue.  Ne10 now builds the library.  Apparently Cmake is not picking up environment variables properly.

**Comment by nuborasi** [comment]
I'm on a Yocto virtual machine having the same problem. I think my cmake expects MATCHES not STREQUAL. Now I can't bet past not being able to compile a simple test program because of  a Change Dir.

**Comment by Phillip-Wang** [comment]
@nuborasi , did you mean we should use MATCHES instead of STREQUAL? Will it fixed the problem of "Change Dir"?

**Comment by nuborasi** [comment]
@Phillip-Wang I think the MATCHES thing was an artifact of something else wrong in my path or something. My real issue was the lack of CFLAGS being set at all in the toolchain file and there was a conflict between soft/hard setup. I had to put SET(CMAKE_C_FLAGS "-mfloat-abi=hard" CACHE STRING "" FORCE) into a toolschain file for the C and CXX compiler tests to pass and the makefiles to be generated.

**Comment by joesavage** [comment]
The problem here isn't actually `STREQUAL` itself (rather than, say, `MATCHES`), but is instead the same issue as #109 and #97 -- the cmake configuration files not checking environment variables properly, and not handling an empty target architecture string properly.
