### ISSUE TITLE
NE10 FFT problem

### ISSUE THREAD

**Issue by fangdu8877** [projectNe10/Ne10#121]
Hi All,

I just start to use the NE10 to do fft. I wrote a test file like below. The input is read number 1 2 3 4.  I run this code on raspberry pi 2 and got an "segmentation fault" error. Please help me correct it. Thanks. 

#include <stdio.h>
#include <stdlib.h>
#include "NE10.h"

 int main()
 {
     
     int fftSize = 4,m;
     ne10_fft_cpx_float32_t *in,*out;
     in= (ne10_fft_cpx_float32_t*) NE10_MALLOC(fftSize * sizeof (ne10_fft_cpx_float32_t));
     out = (ne10_fft_cpx_float32_t*) NE10_MALLOC(fftSize * sizeof (ne10_fft_cpx_float32_t));
     ne10_fft_cfg_float32_t cfg;
     cfg = ne10_fft_alloc_c2c_float32 (fftSize);
     printf("input = \n");
     for(m=0;m<4;m++)
     {
        in[m].r = (float) m;
        in[m].i = 0.0;
        printf("%f + i %f",in[m].r,in[m].i);
     }
     ne10_fft_c2c_1d_float32_c(out, in, cfg, 0);
     printf("output = \n");
     for(m=0;m<4;m++)
     {
        printf("%f + i %f",out[m].r,out[m].i);
     }
     //ne10_fft_c2c_1d_float32_c (out, in, cfg, 1);
     NE10_FREE (in);
     NE10_FREE (out);
     NE10_FREE (cfg);
     return 0;
 }

**Comment by Phillip-Wang** [comment]
Hi, @fangdu8877 , before calling functions in Ne10, please initialize them by `ne10_init()`.
BTW, I would recommend you to use `ne10_fft_c2c_1d_float32` instead of `ne10_fft_c2c_1d_float32_c`.
