### ISSUE TITLE
BuildingNe10.txt - Possibly incorrect environment variable

### ISSUE THREAD

**Issue by Brahmasmi** [projectNe10/Ne10#122]
In the BuildingNe10.txt file, the Android section refers to an environment variable called `NE10_IOS_TARGET_ARCH` on two lines.
(https://github.com/projectNe10/Ne10/blob/master/doc/BuildingNe10.txt#L117-L122)

However, the android_config.cmake file in the android directory refers to `NE10_ANDROID_TARGET_ARCH`.
(https://github.com/projectNe10/Ne10/blob/master/android/android_config.cmake#L55-L59)

We may probably want to refer to the latter in the BuildingNe10.txt file.

**Comment by joesavage** [comment]
Fixed with 7da2e9d818c2a7e653f1faf4cdc30dfa55e8afcc
