### ISSUE TITLE
It is possible to call assembly math modules inline?

### ISSUE THREAD

**Issue by JoeyZhu** [projectNe10/Ne10#126]
for example, I can call ne10_add_float_neon from cpp file, but it is still slow when I call this function  many times enough. I know inline assembly can be done with __asm(...), but it need to rewrite the assembly function. 

I tried to add always_inline key word to head file, but it didn't inlined according to the assembly file generated by cmake.

Thank you!

**Comment by joesavage** [comment]
I suspect the issue here is that you're trying to optimise across a translation unit boundary, which is preventing the compiler from inlining the function call. Could you try compiling and linking with the `-flto` [Link Time Optimisation](https://gcc.gnu.org/wiki/LinkTimeOptimization) flag?
