### ISSUE TITLE
ne10_mulc_float causes segmentation fault

### ISSUE THREAD

**Issue by giuliomoro** [projectNe10/Ne10#130]
Hi,
I compiled Ne10 from source from the branch ee5d856cd9cb8c4a15ace567df4239f4e788d043 .
Running on a Cortex A8
All tests run fine, but as soon As I try to use ne10_mulc_float, I get a segmentation fault.
See the minimal example below, which I compiled with
  gcc -g -o exe ne10-test.c -static -lNE10 -lm -L. -I/usr/include/ne10

Code fails while running
    ne10_mulc_float(dst, src, cst, count);
with a segmentation fault.

````
#include <ne10/NE10.h>
#include <stdio.h>

int main(){
  ne10_float32_t dst[16];
  ne10_float32_t src[16];
  int n;
  for(n = 0; n < 16; n ++){
    dst[n] = n;
  }
  ne10_uint32_t count = 16;
  ne10_float32_t cst = 0.1;
  ne10_mulc_float(dst, src, cst, count);
  for(n = 0; n < 16; n+=4){
    printf("%5.2f %5.2f %5.2f %5.2f\n", *&(dst[n]));
  }
  return 0;
}
````

**Comment by giuliomoro** [comment]
Well, it turns out that ne10_mulc_float is a variable which is not initialized by default.
You should call ne10_mulc_float_neon directly.
I think that the documentation is not very clear:
"This function point could be pointed to one of ne10_add_float_c, ne10_add_float_neon and ne10_add_float_asm."
made me think that the variable would be initialized somewhere (e.g.: at compile time, depending on the target platform).

**Comment by joesavage** [comment]
This is definitely a problem, and you certainly aren't the first person to run into it (see #121 for example). The documentation implies that the function pointers are pre-initialised, and what's worse, the `_init` functions aren't even documented! This should definitely get fixed with some changes to the docs and example code.
