### ISSUE TITLE
NE10 contains non-PIC assembly - fails on Android 6

### ISSUE THREAD

**Issue by AstralStorm** [projectNe10/Ne10#132]
libNe10 contains non-PIC assembly code, even after fixing the CMakeLists.txt to actually add -fpic -Wa,-k (in addition to -pie) and related CFLAGS_ASM_FLAGS.

scanelf tool (Gentoo, from pax-utils package) pinpoints those symbols in our application:
scanelf -qT build/generated/libs-release/armeabi-v7a/libwave.so 
  libwave.so: (memory/data?) [0x3ED03C] in (optimized out: previous ne10_fir_sparse_float_neon) [0x3ECEA1]
  libwave.so: (memory/data?) [0x3ED040] in (optimized out: previous ne10_fir_sparse_float_neon) [0x3ECEA1]
  libwave.so: (memory/data?) [0x3ED1F4] in (optimized out: previous ne10_iir_lattice_float_neon) [0x3ED051]
  libwave.so: (memory/data?) [0x3ED984] in (optimized out: previous ne10_mixed_radix_fft_backward_float32_neon) [0x3ED5B1]
  libwave.so: (memory/data?) [0x3EE954] in (optimized out: previous ne10_mixed_radix_fft_backward_int32_scaled_neon) [0x3EE561]
  libwave.so: (memory/data?) [0x3EF9A4] in (optimized out: previous ne10_mixed_radix_fft_backward_int16_scaled_neon) [0x3EF591]
  build/generated/libs-release/armeabi-v7a/libwave.so

There are probably more, our project does not use whole of libne10.

This issue makes libNe10 unusable on Android 6 targets, which require no text relocations in SELinux policy. Trying to use it results in an application crash or failure to load a shared library.
Force disabling NEON assembly code works, but is not optimal from performance point of view - and there are no versions using intrinsics instead.

**Comment by joesavage** [comment]
Could you verify if this is fixed by #84?

**Comment by joesavage** [comment]
Should be fixed by d89094e3ae12def7c155b815756ddc2d7c4ddbec. Please re-open this issue if it's not!
