### ISSUE TITLE
Speed of fft computation vs opencv 

### ISSUE THREAD

**Issue by KwakJiWon** [projectNe10/Ne10#140]
I found another issue of Ne10 library.
I compared fft speed of N10 to it of opencv, As a result ne10 is slower than opencv.
The sizes of image 160 x 160, padded size is 32768.
Is it true?
Best.

**Comment by james34602** [comment]
I don't know the performance of Ne10 2D FFT.
My experience in 1D FFT on Android, Ne10 is very fast, even faster then FFTW3

**Comment by joesavage** [comment]
Ne10 only provides 1D FFT functions, which — like @james34602 — I have found from experience to be relatively fast. [This performance comparison](https://community.arm.com/groups/android-community/blog/2013/12/18/projectne10-fft-is-updated) also indicates such.

Could you be a bit more specific as to how exactly you're using Ne10's FFT functionality, and what OpenCV functions you're contrasting this against?
