### ISSUE TITLE
Mac Sierra make error for Xcode 8.x

### ISSUE THREAD

**Issue by tipycalFlow** [projectNe10/Ne10#142]
Hi,

I'm trying to use NE10 on XCode 8.1 following the steps in [doc/building.md](https://github.com/projectNe10/Ne10/blob/master/doc/building.md), but `make` with `NE10_IOS_TARGET_ARCH=armv7` fails with this log:

```
ld: library not found for -lcrt1.3.1.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

These are my settings:
1. Mac OS Sierra 10.12.1
2. `NE10_IOS_TARGET_ARCH=armv7`
3. XCode 8.1 project settings:
- Valid Architectures=arm64 armv7 armv7s
- Build Active Architecture Only = NO (both release and debug)

```
[ 81%] Building C object modules/CMakeFiles/NE10.dir/imgproc/NE10_init_imgproc.c.o
[ 81%] Building C object modules/CMakeFiles/NE10.dir/physics/NE10_init_physics.c.o
[ 82%] Linking C static library libNE10.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7 file: libNE10.a(NE10_physics.neon.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7 file: libNE10.a(NE10_rotate_ios.neon.s.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7 file: libNE10.a(NE10_physics_ios.neon.s.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7s file: libNE10.a(NE10_physics.neon.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7s file: libNE10.a(NE10_rotate_ios.neon.s.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7s file: libNE10.a(NE10_physics_ios.neon.s.o) has no symbols
[ 82%] Built target NE10
Scanning dependencies of target NE10_test_static
[ 82%] Building C object samples/CMakeFiles/NE10_test_static.dir/NE10_sample_complex_fft.c.o
[ 83%] Building C object samples/CMakeFiles/NE10_test_static.dir/NE10_sample_fir.c.o
[ 84%] Building C object samples/CMakeFiles/NE10_test_static.dir/NE10_sample_intro.c.o
[ 85%] Building C object samples/CMakeFiles/NE10_test_static.dir/NE10_sample_matrix_multiply.c.o
[ 86%] Building C object samples/CMakeFiles/NE10_test_static.dir/NE10_samples.c.o
[ 87%] Linking CXX executable NE10_test_static
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
ld: library not found for -lcrt1.3.1.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [samples/NE10_test_static] Error 1
make[1]: *** [samples/CMakeFiles/NE10_test_static.dir/all] Error 2
make: *** [all] Error 2
```

**Old Issue:** (Resolved)

I'm trying to use NE10 on XCode 8 and after following the steps in [doc/building.md](https://github.com/projectNe10/Ne10/blob/master/doc/building.md), adding libNE10.a(from ./build/modules/) and headers(from ./inc/) to my project, I get this error :

```
ld: warning: ignoring file /My/Project/Path/libNE10.a, file was built for archive which is not the architecture being linked (x86_64): /My/Project/Path/libNE10.a
Undefined symbols for architecture x86_64: "_ne10_add_float", referenced from:
......
......
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by joesavage** [comment]
Hey, did you manage to resolve this issue? I was able to reproduce the problem, but didn't quite have the time to track down what was causing it.

**Comment by tipycalFlow** [comment]
I tried with a fresh copy of the project folder from the [official website](http://projectne10.github.io/Ne10/) on my personal mac and then created a 'fat' binary of arch64 and armv7 that builds for iOS devices (release build in my iOS project required arch armv7, armv7s and arm64) but not on simulator (requires arch i386). For 'fat' binary, I just did `lipo libNE10_aarch64.a libNE10_armv7.a libNE10.a`

I'm not sure why `NE10_IOS_TARGET_ARCH=armv7` didn't work in my office machine but worked with the fresh copy on my early 2012 MBP.

**Comment by tipycalFlow** [comment]
I think we should look into this issue for `NE10_IOS_TARGET_ARCH=armv7` nonetheless

**Comment by tipycalFlow** [comment]
@joesavage I think the iOS project included in the repository needs to be updated to support Xcode 8, along with make files.

**Comment by joesavage** [comment]
Yes, I think your evaluation here is correct. Unfortunately, I'm not really in a position to make such changes right now, but we can keep this issue open to be resolved some time in the (hopefully near) future.

**Comment by tipycalFlow** [comment]
The cmake error was because it was building for min iOS=5.0 while XCode 8 has OS support from 8.0. I tried cmake with min iOS = 8 and it worked:
```
cmake -DCMAKE_TOOLCHAIN_FILE=../ios/ios_config.cmake .. -DMIN_IOS_VER=8.0
```

So I created the binaries for armv7 and aarch64, then created a fat binary (`lipo -create libNE10_arm64.a libNE10_armv7.a -output libNE10.a`) and added to my iOS project.
Unfortunately, now it gives this error:
```
Undefined symbols for architecture arm64:
  "_ne10_add_float_c", referenced from:
```

**Comment by tipycalFlow** [comment]
The cmake error was because it was building for min iOS=5.0 while XCode 8 has OS support from 8.0. I tried cmake with min iOS = 8 and it worked:
```
cmake -DCMAKE_TOOLCHAIN_FILE=../ios/ios_config.cmake .. -DMIN_IOS_VER=8.0
```

So I created the binaries for armv7 and aarch64, then created a fat binary (`lipo -create libNE10_arm64.a libNE10_armv7.a -output libNE10.a`) and added it to my iOS project.
I checked the new binary's architecture too:
```
$ lipo -info libNE10.a 
-> Architectures in the fat file: libNE10.a are: armv7 armv7s arm64 
```
Now,  I'm able to include `NE10.h` in my c/cpp files, declare my `float` variables as `ne10_float32_t` or call `ne10_init();` and `ne10_fft_c2c_1d_float32(...)` but oddly, running an XCode project with `libNE10.a` as a dependency and executing `ne10_add_float_c(...)` gives this error:
```
Undefined symbols for architecture arm64:
  "_ne10_add_float_c", referenced from:
```
@joesavage Any suggestions?

**Comment by joesavage** [comment]
Glad to hear you've resolved another of the issues. I must say, though, with all the different issues in this thread I'm not entirely sure which bits and pieces helped you where. Would you mind re-outlining the solutions that you've found to work so far and the specific problems that they resolved? If you could, that would be fantastic — not only would it aid others in fixing similar problems, but we might be able to use this information to fix the default xcodeproj at some point in future.

With regards to your second issue, I'm afraid I can't be of much help here. Either the symbols you're looking for aren't in your generated library file for the architecture that Xcode is targeting (definitely worth checking, e.g. via `nm`), or something is wrong in the project configuration that isn't allowing Xcode to properly link your code against the library.

**Comment by tipycalFlow** [comment]
Sure, following are the two things I've learned about the build process so far:

1) For people building for iOS, ensure that cmake command includes DMIN_IOS_VER preference of at least 8.0 so that make runs correctly for armv7/arm64. This is already mentioned in `building.md` though.
```
cmake -DCMAKE_TOOLCHAIN_FILE=../ios/ios_config.cmake .. -DMIN_IOS_VER=8.0
```
2) Generate a fat binary for all target architectures.

**Comment by joesavage** [comment]
So, `MIN_IOS_VER=8.0` resolved the `ld: library not found for -lcrt1.3.1.o` error, and generating a fat binary resolved your question of how to support multiple architectures, is that right? Then your original issue regarding undefined symbols for `x86_64` was, I presume, to do with running the code in the simulator rather than on an actual device. It's probably worth me adding some notes regarding these things to the `building.md` file to help people along that might be encountering similar issues. Was there also another issue where you couldn't get the `armv7` build working on your office machine but it worked fine on your MBP, or was that just the `MIN_IOS_VER` problem?

Assuming those were all of the initial issues, the only remaining issue is then with undefined symbols for `arm64` (i.e. with the `aarch64` part of the fat binary). If I remember correctly, this is actually the issue that I initially managed to reproduce but couldn't quite get to the bottom of. I don't have a test environment to hand at the moment, but if you can check whether the "missing" symbols are actually in the relevant part of the binary file then we can determine if this is an issue with the generated library itself, or with the Xcode project.

**Comment by tipycalFlow** [comment]
Hey @joesavage , the answer to all your questions in the first para is yes.

The undefined symbols error is thrown only for some methods of neon library like `ne10_fft_c2c_1d_float32(...)` but not for others like `ne10_init()`. Methods like `ne10_fft_c2c_1d_float32` further call one of their c/assembly counterparts which might be the reason for the arch error. The same error occurs with the neon sample iOS project too (in NE10_run_test.c).

**Comment by tipycalFlow** [comment]
@joesavage I went through the symbol list with `nm libNE10.a` and indeed there's no symbol there for `ne10_add_float_c` in arch64 but are present for `armv7` and `armv7s`. Any ideas what could be missing?

**Comment by joesavage** [comment]
Upon closer inspection, it looks like the math and physics modules are not enabled by default for aarch64 as they have "not been optimized for aarch64". You can see this in the root `CMakeLists.txt` file [here](https://github.com/projectNe10/Ne10/blob/master/CMakeLists.txt#L85-L93).

If you add `-DNE10_ENABLE_MATH=ON` to your `cmake` invocation before building, it should resolve your issue providing everything compiles correctly. (Who knows if it will.)

**Comment by tipycalFlow** [comment]
I tried `-DNE10_ENABLE_MATH=ON` with option in `cmake` but it fails with errors like:
```
projects/ne10/build/modules/CMakeFiles/NE10.dir/NE10_abs_ios.neon.s:206:11: error: unexpected token at start of statement
        @ absolute values
          ^

projects/ne10/build/modules/CMakeFiles/NE10.dir/NE10_abs_ios.neon.s:211:18: error: vector register expected
        vst3.32 {d0[0], d2[0], d4[0]}, [r0]!
                 ^

projects/ne10/build/modules/CMakeFiles/NE10.dir/NE10_abs_ios.neon.s:250:9: error: unknown directive
        .thumb
        ^

projects/ne10/build/modules/CMakeFiles/NE10.dir/NE10_abs_ios.neon.s:268:26: error: invalid variant 'r3'
        and r3, r2, #3 @ r3 = count % 4; calculate the residual loop
                         ^
```
@joesavage please let me know if you need more info.

**Comment by joesavage** [comment]
Right, of course — I should have thought this through a bit better. The ARMv7 assembly code isn't going to work out of the box with AArch64. In other places, intrinsics and ARMv8-specific assembly are used, but only the ARMv7-specific stuff exists for the math and physics modules right now, hence why they're disabled by default for AArch64.

I'm not sure what the best way to fix this is right now. In the long term, Ne10 really ought to provide updated versions of these functions. But in the short term, maybe you can convince the build infrastructure to only use the C versions of the functions.

**Comment by tipycalFlow** [comment]
Yeah, majority devices now are on 64 bit architecture, so it would definitely be an important update.

**Comment by joesavage** [comment]
Agreed. Since we tackled a few bugs in this thread, though, I'll open up a new issue aimed specifically at the problem of module support on AArch64 that references this one. Thanks again for reporting this.

**Comment by tipycalFlow** [comment]
@joesavage missed one question: what should be the `NE10_IOS_TARGET_ARCH` for iOS simulator that runs on mac architecture `i386` or `x86_64`?

**Comment by joesavage** [comment]
@tipycalFlow I'm not totally sure to be honest with you. The former is the 32-bit target while the latter is the 64-bit target, and [this StackOverflow answer](http://stackoverflow.com/questions/28033635/why-does-the-ios-simulator-require-i386-and-x86-64-symbols-even-though-im-on-an) indicates that you might need the symbols for both. Of course, since Ne10 is a library for the ARM architecture you won't be able to use the optimised versions of any of the functions, but the C versions should work just fine if you can get them to compile correctly for other architectures.
