### ISSUE TITLE
Expected FFT performance

### ISSUE THREAD

**Issue by mbavaro** [projectNe10/Ne10#151]
I am running Ne10 on a Zynq core and Ne10 radix-4 complex float FFT has comparable performance to plain C kissfft. I verified that Ne10 is using neon and calling 
`ne10_mixed_radix_generic_butterfly_float32_neon()`
on FFTs of length 256
I was expecting 3-4 times speed improvement... anybody has the same results?

**Comment by joesavage** [comment]
Oh, is that so? What a bummer! I haven't done any performance comparisons between the C and NEON versions myself, but [previous comparisons on A53](http://web.archive.org/web/20160629173227/https://community.arm.com/groups/android-community/blog/2013/12/18/projectne10-fft-is-updated) seem to indicate that the NEON version can give a ~2–4x performance increase for FFTs of 256 elements in length.

Although I haven't really touched the NEON FFT code in Ne10 all that much, I am fairly familiar with the underlying algorithm. It's very well suited to vectorisation, so it surprises me to hear that it's performing poorly on your platform of choice. Would you mind outlining how exactly you measured the performance here? If the assembly version of the code is being used, perhaps it's the case that the instruction scheduling isn't suitable for the core you're using. And, on the flip side, perhaps the simple C version is getting nicely vectorised and scheduled by your compiler. I would love to see the code used by both versions.

**Comment by mbavaro** [comment]
This morning I added NE10 to the PFFFT benchmark.. these are the results I obtained on a Zynq 

```
| input len |cplx FFTPack|  cplx KISS |  cplx NE10 | cplx PFFFT |
|       64  |      267   |      282   |      760   |      403   |
|       96  |      222   |      188   |      294   |      362   |
|      128  |      258   |      225   |      877   |      397   |
|      160  |      263   |      253   |      306   |      387   |
|      192  |      253   |      235   |      315   |      405   |
|      256  |      288   |      310   |      817   |      437   |
|      384  |      231   |      217   |      318   |      393   |
|      480  |      234   |      232   |      282   |      384   |
|      512  |      256   |      249   |      858   |      419   |
|      640  |      259   |      274   |      310   |      407   |
|      768  |      252   |      259   |      326   |      420   |
|      800  |      241   |      287   |      297   |      398   |
|     1024  |      274   |      323   |      803   |      422   |
|     2048  |      244   |      245   |      682   |      355   |
|     2400  |      214   |      236   |      249   |      336   |
|     4096  |      238   |      274   |      557   |      335   |
|     8192  |      195   |      209   |      484   |      297   |
|     9216  |      193   |      183   |      216   |      282   |
|    16384  |      173   |      183   |      337   |      261   |
```

so indeed NE10 is twice as fast for float radix-2. I compiled on a Ubuntu 16.04 machine with the default compiler options, cmake log is attached here:

[CMakeOutput.txt](https://github.com/projectNe10/Ne10/files/764695/CMakeOutput.txt)

I guess initialisation of NE10 takes way more time than KISS and, since in my previous benchmark I was re-initialising everything in the loop, figures might have been distorted.. sorry for the confusion.

**Comment by joesavage** [comment]
> I guess initialisation of NE10 takes way more time than KISS and, since in my previous benchmark I was re-initialising everything in the loop, figures might have been distorted.. sorry for the confusion.

That'll do it alright — Ne10's FFT factoring process during initialisation is pretty expensive, and isn't at all optimised. No worries, glad the issue is resolved :)
