### ISSUE TITLE
is_NEON_available is not set upon A53 target

### ISSUE THREAD

**Issue by zlqhem** [projectNe10/Ne10#158]
ne10_init() at NE10_init.c searh "neon" word in /proc/cpuinfo. But as the following ARM A53(aarch64) target, it does not contain "neon". So ne10_init() fails to set is_NEON_available as NE10_OK. 
A53 has a feature asimd.
```
MY-A53-TARGET# cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 66.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
...

```

**Comment by joesavage** [comment]
Wow, great catch — it looks like 32-bit cores use the `neon` feature, while 64-bit cores use `asimd`. This is a fairly significant issue, so thanks for reporting it. I'm surprised that it hasn't been fixed sooner, and am somewhat embarrassed on behalf of the project as a whole. I'll fix this right away. Thanks again.

**Comment by joesavage** [comment]
There we go — fixed, and verified on a real machine just to make sure. Thanks again for reporting this!
