### ISSUE TITLE
on armv8, I cannot make install NE10 ，but i can make it . 

### ISSUE THREAD

**Issue by zhaodeming** [projectNe10/Ne10#160]
in Native compilation on *nix platforms, i can build the project . but when i make install the NE10 ，the error show that it can find 'install' , in mikefile ,i cannot find 'make install' instruction.
in addition , when i make the project , the terminal show ’memory allocation failed‘
what should i do ?

**Comment by joesavage** [comment]
Is this related to #161 and thus also resolved?
