### ISSUE TITLE
in the condition of aarch64 ，i cannot build the project ,but not gain the sample of NE10_test_static 

### ISSUE THREAD

**Issue by zhaodeming** [projectNe10/Ne10#161]
i cannot gain the "samples" in the "build ". in addition in the "makefile" i cannot find the "make install" instruction. why ?? the compiler be not aware of Ne10's library and header files — those within build/modules/ and inc/.  i cannot apply the "NE10_h".

**Comment by zhaodeming** [comment]
thankyou joesavage , i solve my question . i don't make install . i put "*.h"and“NE10_sample_fir.c”in a folder.
i learn 'cmake',and understand the process of the 'building NE10' . on the aarch64 , building the project ,it don't add the folder of '../build/samples' . but i use g++ to build ‘NE10_sample_fir.c’
g++ NE10_sample_fir.c -o NE10_sample_fir -lm -lNE10

**Comment by joesavage** [comment]
Great to hear you've managed to resolve this.
