### ISSUE TITLE
Building NE10

### ISSUE THREAD

**Issue by peterlaurie** [projectNe10/Ne10#162]
I'm trying to install NE10 on a BeagleBone Black under liniux.  

I'm following the instructions for 'Native compilation on *nix platforms'.

the line:

cmake -DGNULINUX_PLATFORM=ON ..
produces errors:

root@beaglebone:~/dsp/NE10/build# cmake -DGNULINUX_PLATFORM=ON ..
-- Target architecture: armv7
-- Building type: RELEASE
CMake Error at CMakeLists.txt:147 (add_subdirectory):
  add_subdirectory given source "modules" which is not an existing directory.

CMake Error at CMakeLists.txt:150 (add_subdirectory):
  add_subdirectory given source "samples" which is not an existing directory.

-- Configuring incomplete, errors occurred!
----------------------
I have created the directories .../build/modules and .../build/samples
What's going wrong?

**Comment by joesavage** [comment]
Hi, Peter. Hmm, that's a strange one, and may be the same problem as #161. Running the following on my local machine, CMake operates as expected:

```
$ git clone https://github.com/projectNe10/Ne10
Cloning into 'Ne10'...
remote: Counting objects: 5416, done.
remote: Total 5416 (delta 0), reused 0 (delta 0), pack-reused 5416
Receiving objects: 100% (5416/5416), 6.34 MiB | 546.00 KiB/s, done.
Resolving deltas: 100% (4100/4100), done.
Checking connectivity... done.
$ cd Ne10
$ mkdir build && cd build
$ cmake -DGNULINUX_PLATFORM=ON ..
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target architecture: 
-- Building type: RELEASE
-- Configuring done
-- Generating done
-- Build files have been written to: /path/Ne10/build
```

Are you using the master branch of this repository as I did above, or a tagged release? And what version of CMake are you using? (I'm on version 3.5.1, as indicated by `cmake --version`)

**Comment by peterlaurie** [comment]
Joe

Thanks for your response.

I'm not familiar with Github, but the page I copied the script from is 
titled


  projectNe10 <https://github.com/projectNe10>/*Ne10
  <https://github.com/projectNe10/Ne10>*

and says it is branch master

Version is 3.7.2

Peter

**Comment by joesavage** [comment]
Can you just confirm what you mean by having "copied the script"? It sounds like you've probably just cloned the master branch via something like `git clone https://github.com/projectNe10/Ne10`, but I'm not entirely sure from your description.

**Comment by peterlaurie** [comment]
I went to 
https://raw.githubusercontent.com/projectNe10/Ne10/master/CMakeLists.txt
hit the 'raw' button and got a text version of the script. I selected all of that and pasted it into Word and saved the file as 'plain text'
I uploaded that to the Beag;leBone via PSCP as a text file, and saved it in ~/dsp/NE10. I went to ../ build and 
ran:
cmake -DGNULINUX_PLATFORM=ON .. which produces the errors as above

**Comment by joesavage** [comment]
I see. Well, that certainly explains why the project isn't building correctly on your machine — you haven't downloaded any of the actual code! It sounds like you need a slightly better understanding of your build environment in order to get this working. It might be worth reading a little bit about bash and git in particular.

If you try running the set of commands outlined [here](https://github.com/projectNe10/Ne10/issues/162#issuecomment-288718196) — that is, entering the bits that come after a `$` symbol in a shell on your BeagleBone — you should find that the project builds as you might expect. If you don't mind me asking, what is it that you're trying to use Ne10 for here exactly? If you don't quite understand the how the build process works, I suspect you might have some issues figuring out how to actually use the library in your project too.

**Comment by peterlaurie** [comment]
Joe

I realise that there's probably a substantial  misunderstanding at work 
here.

You probably think of my BeagleBone (BBB) as a standalone Unix machine 
with screen and keyboard, connected to the web.

In fact, since it is going to be a hearing aid that people carry in 
their pockets, I run it via USB and Putty from my Win7 PC..  It has no 
screen or keyboard and is only occasionally connected to the web via 
ethernet.

Since we need to use the PRUs I have had to disable DPMI - if that's 
relevant.

I should have realised that the NE10 build instructions we were 
discussing yesterday were probably (though I don't remember seeing it 
explicitly stated)  applicable to the standalone situation.

To build things via Putty I have to downlaod the necessary files onto my 
PC and then transfer them by PSCP to the BBB. To my surpise this worked 
easily for Cmake, so I thought I'd be able to do the same thing for 
NE10. But no.

I'd have thought there are two possible courses of action.

1. I download the necessary files via the PC, stow them in suitable 
places on the BBB and Cmake  NE10

2. Connect to the web via ethernet and somehow persuade Github to supply 
the files as if the BBB were a standalone machine.

What do you think?

My aplogies for having been rather fretful yesterday evening.

Peter

**Comment by joesavage** [comment]
Hey, Peter. No worries at all, and thanks for the context. It's always hard to gauge the understanding and abilities of those reporting issues, so apologies if my previous reply was overly simplistic or lacking in details.

If you download [this zip file](https://github.com/projectNe10/Ne10/archive/master.zip) on your Windows machine, unzip it, and then send the unzipped directory to the BBB over PSCP, you should be able to enter the directory via PuTTY (using `cd` or what have you) on the BBB and then follow the build instructions as outlined in [building.md](https://github.com/projectNe10/Ne10/blob/master/doc/building.md) (where $NE10_PATH is the location to which you copied the files). Please do let me know if you have any further questions about this.

**Comment by peterlaurie** [comment]
On 25-Mar-17 11:18 AM, Joe Savage wrote:
>
> Hey, Peter. No worries at all, and thanks for the context. It's always 
> hard to gauge the understanding and abilities of those reporting 
> issues, so apologies if my previous reply was overly simplistic or 
> lacking in details.
>
There's an amazing amount of stuff I don't understand
>
> If you download this zip file 
> <https://github.com/projectNe10/Ne10/archive/master.zip> on your 
> Windows machine, unzip it, and then send the unzipped directory to the 
> BBB over PSCP, you should be able to enter the directory via PuTTY 
> (using |cd| or what have you) on the BBB and then follow the build 
> instructions as outlined in building.md 
> <https://github.com/projectNe10/Ne10/blob/master/doc/building.md> 
> (where $NE10_PATH is the location to which you copied the files). 
> Please do let me know if you have any further questions about this.
>

Thanks for this. Do I need Cmake? RAM is a bit tight on the BBB, so if 
it can go that would be helpful.

Peter

**Comment by peterlaurie** [comment]
Joe

> If you download this zip file 
> <https://github.com/projectNe10/Ne10/archive/master.zip> on your 
> Windows machine, unzip it, and then send the unzipped directory to the 
> BBB over PSCP, you should be able to enter the directory via PuTTY 
> (using |cd| or what have you) on the BBB and then follow the build 
> instructions as outlined in building.md 
> <https://github.com/projectNe10/Ne10/blob/master/doc/building.md> 
> (where $NE10_PATH is the location to which you copied the files). 
> Please do let me know if you have any further questions about this.
>
Thanks for this. I've got Ne10-master/ copied to the BBB:

~/dsp/NE10/Ne10-master

I assume that ../Ne10-master is $NE10_PATH, so I cd into it and do the 
build commands, then export... and cmake....

and get an error message:  CMake Error: The source directory 
"/root/dsp/NE10/Ne10-master/build" does not appear to contain 
CMakeLists.txt.

That file is in Ne10-master/

What should I have done?

Peter


.

**Comment by peterlaurie** [comment]
Joe


I've done:

~/dsp/NE10/Ne10-master

I assume that ../Ne10-master is $NE10_PATH, so I cd into it and do the 
build commands, then export... and cmake....

and get an error message:  CMake Error: The source directory 
"/root/dsp/NE10/Ne10-master/build" does not appear to contain 
CMakeLists.txt.

I copied CMakeLists.txt to ../build

cmake .. then produced an error:


CMake Error at CMakeLists.txt:173 (add_subdirectory):
   add_subdirectory given source "modules" which is not an existing 
directory.


CMake Error at CMakeLists.txt:176 (add_subdirectory):
   add_subdirectory given source "samples" which is not an existing 
directory.

Peter

**Comment by joesavage** [comment]
Hi Peter,

Unfortunately I don't have the time to walk through the build process step-by-step with you, but it seems like you're issuing the build commands incorrectly. Particularly your CMake error indicates that you were trying to run `cmake .` (or something similar, hence the error "The source directory "/root/dsp/NE10/Ne10-master/**build**" does not appear to contain CMakeLists.txt"), while the command `cmake ..` should instead be used (with any appropriate additional flags, as outlined [here](https://github.com/projectNe10/Ne10/blob/master/doc/building.md)).

I'm going to close this issue now, as it appears to be purely with the build process. Best of luck fixing your problem.

**Comment by peterlaurie** [comment]
Joe

Thanks for your help.


It became apparent that NE10 and Cmake were altogether to substantial 
for what we need, which was just some inner loop intrinsics.


Peter
