### ISSUE TITLE
in the condition of aarch64 or armv8 , i need to use neon or the module of math

### ISSUE THREAD

**Issue by zhaodeming** [projectNe10/Ne10#164]
hello  joesavage:
can you help me?
on the armv8 , i need to use math ,example add and multiple . but i execute the procedure in the neon . 
when i compile the procedure , what i need to add in 'gcc xxx.c -lNE10'?

**Comment by zhaodeming** [comment]
or how can i build the module of math in the NE10 in the condition of aarch64.

**Comment by joesavage** [comment]
Unfortunately, I don't think it's currently possible to build Ne10's NEON-optimised math or physics modules for AArch64 as many of the routines are written in ARMv7 assembly. This is noted in #150 as something that we should try to rectify in future, but for the moment I'm afraid you're out of luck.
