### ISSUE TITLE
2d fft usage

### ISSUE THREAD

**Issue by Isco-Chen** [projectNe10/Ne10#166]
Hi,
I'd like to use 2d fft (image process application) in my project, but it seems that there's only 1d fft code in this project. Is there any suggestion about the 2d fft achievement?
Thanks!

**Comment by joesavage** [comment]
Hey there. You can compose higher dimensional FFTs fairly straightforwardly out of simple 1D FFTs. In this case, if I'm not mistaken, you could perform a 1D real-to-complex FFT on each row of your image data, and then perform complex-to-complex 1D FFTs on the columns of the results, yielding the 2D FFT of the original input data as desired.

**Comment by Isco-Chen** [comment]
Thanks for you reply! That's what I'm trying to do.
