### ISSUE TITLE
Running NE10Demo project in iOS Simulator

### ISSUE THREAD

**Issue by tausiq** [projectNe10/Ne10#168]
I am trying to run the `master/ios/NE10Demo` project in iOS Simulator. But got the following error, 

`No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=x86_64, VALID_ARCHS=i386)`

Is it runnable in iOS Simuator?

**Comment by joesavage** [comment]
Unfortunately, the iOS demo application included with Ne10 is not runnable in iOS Simulator. This is due to the fact that the simulator executes x86 code natively, but the demo application relies on being able to execute ARM-specific NEON-optimised versions of various Ne10 routines.
