### ISSUE TITLE
R2C FFT of size 4 yields incorrect result

### ISSUE THREAD

**Issue by vinayak-garg** [projectNe10/Ne10#169]
Hi,
I am testing `ne10_fft_r2c_1d_float32_neon`, and I have done init properly as mentioned in sample program. If the FFT size is 4, after execution of above function, the output pointer is set to NULL.
For FFT size of 8, it works correctly.
Since I am using Ne10 as black box, I am not able to debug inside. However by looking at the code in `ne10_mixed_radix_r2c_butterfly_float32_neon`, I suspect that FFT size of 4 is not supported.
Can anyone please verify this?

Thanks!

**Comment by joesavage** [comment]
Hey there. Can you clarify what you mean by "the output pointer is set to NULL"? `ne10_fft_r2c_1d_float32_neon` doesn't return a pointer of any kind — instead, opting to write the result into a provided buffer — so I'm not sure I understand the problem here.

**Comment by joesavage** [comment]
Follow up: I decided to test out some four-sample FFTs for myself to see if I could reproduce any issues. As it turns out, I think you're right — Ne10 has an issue with real-to-complex (but not complex-to-complex) FFTs of size four. For instance, I'm seeing the following results using Ne10's C2C and R2C unoptimised FFT routines:

```
# Complex-to-Complex FFT (Correct!)
IN[ 0]: 18.0000 + 0.0000i		OUT[ 0]: 114.0000 + 0.0000i
IN[ 1]: 38.0000 + 0.0000i		OUT[ 1]:  -7.0000 - 5.0000i
IN[ 2]: 25.0000 + 0.0000i		OUT[ 2]: -28.0000 + 0.0000i
IN[ 3]: 33.0000 + 0.0000i		OUT[ 3]:  -7.0000 + 5.0000i

# Real-to-Complex FFT (Incorrect!)
IN[ 0]: 18.0000		OUT[ 0]: 114.0000 +  0.0000i
IN[ 1]: 38.0000		OUT[ 1]:  51.0000 - 13.0000i
IN[ 2]: 25.0000		OUT[ 2]: -28.0000 +  0.0000i
IN[ 3]: 33.0000		OUT[ 1]:  51.0000 + 13.0000i
```

It looks like the root cause here is that to process a R2C FFT of four real samples, Ne10 first treats the input as a C2C FFT of two complex samples. However, C2C FFTs of size two don't appear to be supported properly (despite the documentation stating otherwise). I'll mark this as a bug.

**Comment by joesavage** [comment]
I've also just verified that this specific case can be fixed relatively easily via additional base cases in the C code. For instance, the following patch fixes float32 C2C FFTs of two complex samples / R2C FFTs of four real samples:

```patch
diff --git a/modules/dsp/NE10_fft_float32.c b/modules/dsp/NE10_fft_float32.c
index ff1fb62..afd6849 100644
--- a/modules/dsp/NE10_fft_float32.c
+++ b/modules/dsp/NE10_fft_float32.c
@@ -192,7 +192,7 @@ static void ne10_mixed_radix_butterfly_float32_c (ne10_fft_cpx_float32_t *out,
         stage_count--;
         fstride /= 4;
     }
-    else // first_radix == 4, for our factoring this means nfft is of form 2^{even}
+    else if (first_radix == 4) // For our factoring this means nfft is of form 2^{even} >= 4
     {
         for (f_count = fstride; f_count; f_count--)
         {
@@ -239,6 +239,14 @@ static void ne10_mixed_radix_butterfly_float32_c (ne10_fft_cpx_float32_t *out,
         stage_count--;
         fstride /= 4;
     }
+    else if (__builtin_expect (first_radix == 2, 0)) // Special case, nfft = 2
+    {
+        dst[0].r = src[0].r + src[1].r;
+        dst[0].i = src[0].i + src[1].i;
+        dst[1].r = src[0].r - src[1].r;
+        dst[1].i = src[0].i - src[1].i;
+        return;
+    }
 
     // The next stage should read the output of the first stage as input
     in = out;
@@ -519,7 +527,7 @@ static void ne10_mixed_radix_butterfly_inverse_float32_c (ne10_fft_cpx_float32_t
             }
         }
     }
-    else // first_radix == 4, nfft is of form 2^{even}
+    else if (first_radix == 4) // nfft is of form 2^{even}
     {
         for (f_count = fstride; f_count; f_count--)
         {
@@ -575,6 +583,14 @@ static void ne10_mixed_radix_butterfly_inverse_float32_c (ne10_fft_cpx_float32_t
             }
         }
     }
+    else if (__builtin_expect (first_radix == 2, 0)) // Special case, nfft = 2
+    {
+        dst[0].r = (src[0].r + src[1].r) * one_by_nfft;
+        dst[0].i = (src[0].i + src[1].i) * one_by_nfft;
+        dst[1].r = (src[0].r - src[1].r) * one_by_nfft;
+        dst[1].i = (src[0].i - src[1].i) * one_by_nfft;
+        return;
+    }
 
     // The next stage should read the output of the first stage as input
     in = out;
diff --git a/modules/dsp/test/test_suite_fft_float32.c b/modules/dsp/test/test_suite_fft_float32.c
index dcb9b11..41d3baf 100644
--- a/modules/dsp/test/test_suite_fft_float32.c
+++ b/modules/dsp/test/test_suite_fft_float32.c
@@ -46,7 +46,7 @@
 
 /* Max FFT Length and double buffer for real and imag */
 #define TEST_LENGTH_SAMPLES (32768)
-#define MIN_LENGTH_SAMPLES_CPX (4)
+#define MIN_LENGTH_SAMPLES_CPX (2)
 #define MIN_LENGTH_SAMPLES_REAL (MIN_LENGTH_SAMPLES_CPX*2)
 #define SNR_THRESHOLD_FLOAT32 90.0f
 
@@ -102,7 +102,7 @@ void test_fft_c2c_1d_float32_conformance()
         fftSize = baseSize;
         while (factor && fftSize <= TEST_LENGTH_SAMPLES)
         {
-            if (fftSize % NE10_FFT_PARA_LEVEL == 0)
+            if (fftSize == 2 || fftSize % NE10_FFT_PARA_LEVEL == 0)
             {
                 fprintf (stdout, "FFT size %d\n", fftSize);
                 flag_result = test_c2c_alloc (fftSize);

```

Similar changes could be made for the int32 and int16 variants. This would nicely round off the power-of-two FFT functionality in Ne10, so it's probably worth me going ahead and commiting a change to do exactly this shortly. @vinayak-garg: would this resolve your problem?

Unfortunately, this still won't resolve the broader issue Ne10 currently has with optimised FFTs for sizes that are not wholly divisible by four — outlined in #135. But at least this should mean that the library's coverage for power-of-two FFTs is more thorough, and indeed that the documentation for the supported sizes in R2C FFTs is more accurate.

**Comment by vinayak-garg** [comment]
Thanks @joesavage for looking into this. Can you please check the neon implementation - `ne10_fft_r2c_1d_float32_neon` as well once.

I built debug version of Ne10, to see where I am getting SIGSEGV. (Initially I thought SIGSEGV was due to my code referencing NULL pointer, but seems that's not the case).

So I found I am getting fault on line `mstride     = factors[ (stage_count << 1) - 1 ];` inside `ne10_mixed_radix_r2c_butterfly_float32_neon`.

Here is the snapshot of locals inside Android Studio - 
<img width="596" alt="screen shot 2017-06-24 at 12 39 38 am" src="https://user-images.githubusercontent.com/1853535/27496947-c93458e8-5875-11e7-8b5f-391dff9fb5f1.png">



Thanks!

**Comment by joesavage** [comment]
Ah, I see. It looks like my assumption that R2C FFTs always rely on their half-sized C2C counterparts doesn't always hold true — though this is true of the `ne10_fft_r2c_1d_float32_neon` in [NE10_fft_float32.neon.c](https://github.com/projectNe10/Ne10/blob/fee112eb2278469e7cfe2516dffa2ecfa5ad4c9a/modules/dsp/NE10_fft_float32.neon.c), you're quite right that it doesn't seem to hold true for the version in [NE10_rfft_float32.neonintrinsic.c](https://github.com/projectNe10/Ne10/blob/fee112eb2278469e7cfe2516dffa2ecfa5ad4c9a/modules/dsp/NE10_rfft_float32.neonintrinsic.c), which has some separate logic that might be problematic. Those local variables look highly suspect too, so it looks like the factoring process might have gone slightly wrong. I'll try to look more closely at (and properly test) this NEON side of the R2C functionality next week if I can find the time.
