### ISSUE TITLE
Link Error on ARMv8

### ISSUE THREAD

**Issue by ChuckNXP** [projectNe10/Ne10#170]
I am trying to compile the NE10_sample_matrix_multiply program and get an error with linking: undefined reference to `ne10_mulmat_3x3f'.  Sure enough that symbol is not in my libNE10.a.

I found a comment in <NE10_Project>.CMakeList.

if("${NE10_TARGET_ARCH}" STREQUAL "armv7")
    # Math module has not been optimized for aarch64.
    option(NE10_ENABLE_MATH "Build math functionalities to NE10" ON)
    # Physics module has not been optimized for aarch64.
    option(NE10_ENABLE_PHYSICS "Build physics functionalities to NE10" ON)
endif()

I would re-build libNE10.a for NE10_TARGET_ARCH=armv7 just to see if the problem goes away but I am having trouble uninstalling the existing library.

Could using NE10_TARGET_ARCH=aarch64 be my problem?   I'll have to overcome my uninstall problem if it is.

Here is my command line:
gcc  ./obj/NE10_sample_matrix_multiply.o -L/home/chuck/ne10/projectNe10-Ne10-0c9f576/build/modules -lNE10 -lm  -o ./bin/NE10_sample_matrix_multiply.elf
./obj/NE10_sample_matrix_multiply.o: In function `main':
NE10_sample_matrix_multiply.c:(.text.startup+0x174): undefined reference to `ne10_mulmat_3x3f'
NE10_sample_matrix_multiply.c:(.text.startup+0x184): undefined reference to `ne10_mulmat_3x3f'

(I've tried putting the linked directories ahead of the *.o file since I usually mess that up without impacting the error.)

I think I will also try compiling NE10_sample_complex_fft.c to see if it works.  I see a bunch of dsp functions among the symbols in my libNE10.a.

**Comment by ChuckNXP** [comment]
Yes, I can build and run NE10_sample_complex_fft in my environment.  It must be that the math functions are not available in the libNE10.a I built.  I wonder how to build an alternate libNE10.a for an armv7 target without deleting my existing files?  And does it make any sense to run an armv7 libNE10.a on an armv8?

**Comment by vinayak-garg** [comment]
Check out issue #150 . Math and physics are not supported for arm64-v8a. So when you build libNE10.a for aarch64, math routines would be absent. I use the command below to check if the needed routine is present in the built binary - 
`strings libNE10.a | grep mulmat`
This returned nothing, as I have also built libNE10.a for aarch64.

You can't run armv7 libNE10.a on an arm64-v8a device.

**Comment by joesavage** [comment]
Yep, @vinayak-garg is exactly right. Sadly, the math and physics modules in Ne10 only support ARMv7 at the minute, as described in #150.
