### ISSUE TITLE
build for android  [shows No such file or directory  #include <stdio.h>]

### ISSUE THREAD

**Issue by heyitao** [projectNe10/Ne10#187]
Here the problem I have met : 
heyitaodeMacBook-Pro:Downloads heyitao$ cd projectNe10
heyitaodeMacBook-Pro:projectNe10 heyitao$  cd build
heyitaodeMacBook-Pro:build heyitao$ export ANDROID_NDK=/Users/heyitao/Library/Android/sdk/ndk-bundle
heyitaodeMacBook-Pro:build heyitao$ export NE10_ANDROID_TARGET_ARCH=aarch64
heyitaodeMacBook-Pro:build heyitao$ cmake -DCMAKE_TOOLCHAIN_FILE=../android/android_config.cmake ..
-- Target architecture: aarch64
-- Building type: RELEASE
-- Loaded toolchain:
    /Users/heyitao/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
    /Users/heyitao/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++
    /Users/heyitao/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-as
-- CMAKE_C_FLAGS:
     -fno-strict-aliasing -O2 -DNDEBUG --sysroot=/Users/heyitao/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64/ -pie
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_TOOLCHAIN_FILE

-- Build files have been written to: /Users/heyitao/Downloads/projectNe10/build
heyitaodeMacBook-Pro:build heyitao$ make
Scanning dependencies of target NE10
[  0%] Building C object modules/CMakeFiles/NE10.dir/math/NE10_abs.c.o
In file included from /Users/heyitao/Downloads/projectNe10/modules/math/NE10_abs.c:32:0:
/Users/heyitao/Downloads/projectNe10/inc/NE10_types.h:39:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
make[2]: *** [modules/CMakeFiles/NE10.dir/math/NE10_abs.c.o] Error 1
make[1]: *** [modules/CMakeFiles/NE10.dir/all] Error 2
make: *** [all] Error 2
heyitaodeMacBook-Pro:build heyitao$

**Comment by koala99** [comment]
中国人吧， just change your ndk version, i met the same problem on mac ,change ndk version can solve this
