### ISSUE TITLE
Build issue for aarch64

### ISSUE THREAD

**Issue by pilakedh** [projectNe10/Ne10#189]
I get the error when i use the android build with aarch64-linux-android-g++ as compiler

> In file included from /usr/include/math.h:472:0,
>                  from /home/arbeit/Ne10-master/inc/NE10_types.h:42,
>                  from /home/arbeit/Ne10-master/modules/dsp/NE10_fft.c:47:
> /home/parallels/arbeit/Ne10-master/modules/dsp/NE10_fft.c: In function 'ne10_fft_generate_twiddles_line_int32':
> /usr/include/bits/mathinline.h:746:1: error: impossible constraint in 'asm'
>  __inline_mathcodeNP (floor, __x, \
>  ^
> /usr/include/bits/mathinline.h:746:1: error: impossible constraint in 'asm'

**Comment by pilakedh** [comment]
Also this issue on another linux distribution

> NE10_fft_cplx_ops.h:57:37: error: cast from 'ne10_fft_cpx_int32_t*' to 'intptr_t {aka int}' loses precision [-fpermissive]
>      ptr_b = (T *)((intptr_t)(ptr_a) ^ (intptr_t)(ptr_b));

**Comment by Phillip-Wang** [comment]
Hi @pilakedh , could you kindly provide information about your g++ version?

**Comment by pilakedh** [comment]
this is my config.cmake file and you can see my compiler here

set(CMAKE_SYSTEM_NAME Linux)
set(ANDROID_PLATFORM ON)
set( CMAKE_C_COMPILER aarch64-linux-android-gcc )  
set( CMAKE_CXX_COMPILER aarch64-linux-android-g++ ) 
set( CMAKE_ASM_COMPILER aarch64-linux-android-as ) 

find_program(CMAKE_AR NAMES "aarch64-linux-android-ar")  
mark_as_advanced(CMAKE_AR)   
find_program(CMAKE_RANLIB NAMES "aarch64-linux-android-ranlib")
mark_as_advanced(CMAKE_RANLIB)
