### ISSUE TITLE
`#include <math.h>` in inc/*.h files have no reason to be there

### ISSUE THREAD

**Issue by giuliomoro** [projectNe10/Ne10#212]
this actually causes problems if `NE10.h` is included in a file that then includes `<cmath>`.
The `#include <math.h>` line should be in the `.c` files where appropriate. A number of other includes in `NE10.h` and a bit all over the place are pointless and should be removed.

**Comment by Phillip-Wang** [comment]
Thank you for contribution. I agree it make no sense to include the headers in the API headers. Could you update your pull request to fix the failures. It is OK to remove the NULL in our macros.
One more thing, please make sure you have commit the change with the Sign-off-by line. Refer to Contributing.md for this requirement.
