### ISSUE TITLE
Double precision support

### ISSUE THREAD

**Issue by Mat29** [projectNe10/Ne10#24]
Hi there,

I am successfully using the Ne10 library for an audio processing project inside the android ndk. 
The library works fine and has great performance on the devices I tested so far.

An important feature for me would be that the library supports double precision as well.
Could someone tell me if double support is planed to be released?
If yes, any idea when the release might be expected?

I'm looking forward to the next release of this very useful library.
Would be great if we could have complex format support, convolution and fft as well.

Thanks a lot for the reply.
Best regards,
Mat

**Comment by vinayak-garg** [comment]
Hi team,
Are you planning on adding double precision support? We want to use Ne10 functions on ARMv8 android devices.

Thanks!

**Comment by aaronfranke** [comment]
@mdupuy What is the current status of double-precision support? Does the current market of Android devices still make this infeasible? As far as I know, newer Android devices have hardware double support.

**Comment by tonykuttai** [comment]
Hi Team,

Would like to know the status of Double precision support.

Thanks !
@mdupuy
