### ISSUE TITLE
Build for Android in Mac Fail

### ISSUE THREAD

**Issue by jamesguo** [projectNe10/Ne10#54]
# I changed something in android-config.cmake like this

`set(ANDROID_TOOLCHAIN_PATH "/Users/James/Work/adt-bundle-mac-x86_64-
20130717/android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/
darwin-x86_64/arm-linux-androideabi/bin")
set(CMAKE_C_COMPILER ${ANDROID_TOOLCHAIN_PATH}/gcc)
set(CMAKE_CXX_COMPILER ${ANDROID_TOOLCHAIN_PATH}/g++)
set(CMAKE_ASM_COMPILER ${ANDROID_TOOLCHAIN_PATH}/as)`
# then after make got an error:

> James-AirtekiMacBook-Air:build James$ cmake -DCMAKE_TOOLCHAIN_FILE=/Users/James/Work/Ne10-master/
> android/android_config.cmake ..
> -- The C compiler identification is unknown
> -- The ASM compiler identification is GNU
> -- Found assembler: /Users/James/Work/adt-bundle-mac-x86_64-20130717/
> android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/
> arm-linux-androideabi/bin/as
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - failed
> loaded toolchain:
>     OFF/arm-linux-androideabi-gcc
>     OFF/arm-linux-androideabi-g++
>     OFF/arm-linux-androideabi-as
>     OFF/arm-linux-androideabi-ar
>     OFF/arm-linux-androideabi-ranlib
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/James/Work/Ne10-master/build
> James-AirtekiMacBook-Air:build James$ make
> Scanning dependencies of target NE10
> **[  1%] Building C object modules/CMakeFiles/NE10.dir/math/NE10_abs.c.o
> gcc: error trying to exec 'cc1': execvp: No such file or directory**
> make[2]: **\* [modules/CMakeFiles/NE10.dir/math/NE10_abs.c.o] Error 1
> make[1]: **\* [modules/CMakeFiles/NE10.dir/all] Error 2
> make: **\* [all] Error 2
> James-AirtekiMacBook-Air:build James$

**Comment by dhanvarsh03** [comment]
error: unknown target CPU 'armv7-a'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cannonlake, icelake-client, icelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, x86-64
make: *** [gst-build-armeabi-v7a/gstreamer_android.o] Error 1


Can anyone please help me on this issue????

**Comment by edidada** [comment]
> error: unknown target CPU 'armv7-a'
> note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cannonlake, icelake-client, icelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, x86-64
> make: *** [gst-build-armeabi-v7a/gstreamer_android.o] Error 1
> 
> Can anyone please help me on this issue????

I also meet this
