### ISSUE TITLE
Complex FFT Conformance testing

### ISSUE THREAD

**Issue by billChadwick** [projectNe10/Ne10#78]
Using some known answer tests from another project I find that many of the 16 bit complex FFT functions are giving the wrong answer. I have modified the Ne10 conformance testing for 16 bit complex FFT to find the worst result amongst the individual output values.

See below for more details.

With your original conformance test (modified to print out SNRs) the SNRs are

----------test_fft_c2c_1d_int16_conformance start
FFT size 4
FFT forward unscaled size 4, SNR inf
FFT inverse unscaled size 4, SNR inf
FFT forward scaled size 4, SNR 69.288
FFT inverse scaled size 4, SNR 69.288
FFT size 8
FFT forward unscaled size 8, SNR 57.224
FFT inverse unscaled size 8, SNR 61.993
FFT forward scaled size 8, SNR 62.381
FFT inverse scaled size 8, SNR 63.630
FFT size 16
FFT forward unscaled size 16, SNR 58.361
FFT inverse unscaled size 16, SNR 57.899
FFT forward scaled size 16, SNR 60.473
FFT inverse scaled size 16, SNR 62.324
FFT size 32
FFT forward unscaled size 32, SNR 60.943
FFT inverse unscaled size 32, SNR 60.358
FFT forward scaled size 32, SNR 58.101
FFT inverse scaled size 32, SNR 57.066
FFT size 64
FFT forward unscaled size 64, SNR 57.410
FFT inverse unscaled size 64, SNR 57.696
FFT forward scaled size 64, SNR 54.565
FFT inverse scaled size 64, SNR 54.674
FFT size 128
FFT forward unscaled size 128, SNR 58.646
FFT inverse unscaled size 128, SNR 59.541
FFT forward scaled size 128, SNR 50.330
FFT inverse scaled size 128, SNR 50.689
FFT size 256
FFT forward unscaled size 256, SNR 56.172
FFT inverse unscaled size 256, SNR 55.958
FFT forward scaled size 256, SNR 46.857
FFT inverse scaled size 256, SNR 46.777
FFT size 512
FFT forward unscaled size 512, SNR 58.343
FFT inverse unscaled size 512, SNR 58.434
FFT forward scaled size 512, SNR 43.908
FFT inverse scaled size 512, SNR 43.891
FFT size 1024
FFT forward unscaled size 1024, SNR 55.729
FFT inverse unscaled size 1024, SNR 55.455
FFT forward scaled size 1024, SNR 40.641
FFT inverse scaled size 1024, SNR 40.811
FFT size 2048
FFT forward unscaled size 2048, SNR 58.097
FFT inverse unscaled size 2048, SNR 57.980
FFT forward scaled size 2048, SNR 37.833
FFT inverse scaled size 2048, SNR 37.880
FFT size 4096
FFT forward unscaled size 4096, SNR 55.668
FFT inverse unscaled size 4096, SNR 55.329
FFT forward scaled size 4096, SNR 34.611
FFT inverse scaled size 4096, SNR 34.670
                           1 run  0 failed                            

If I modify your test to use the worst SNR of a single point's real or imaginary part I get

----------test_fft_c2c_1d_int16_conformance start
FFT size 4
FFT forward unscaled size 4, SNR 99999.000
FFT inverse unscaled size 4, SNR 99999.000
FFT forward scaled size 4, SNR 65.747
FFT inverse scaled size 4, SNR 65.747
FFT size 8
FFT forward unscaled size 8, SNR 37.385
FFT inverse unscaled size 8, SNR 43.346
FFT forward scaled size 8, SNR 52.770
FFT inverse scaled size 8, SNR 46.729
FFT size 16
FFT forward unscaled size 16, SNR 41.845
FFT inverse unscaled size 16, SNR 43.825
FFT forward scaled size 16, SNR 34.320
FFT inverse scaled size 16, SNR 34.320
FFT size 32
FFT forward unscaled size 32, SNR 39.085
FFT inverse unscaled size 32, SNR 44.861
FFT forward scaled size 32, SNR 13.979
test_fft_c2c_1d_int16_conformance Line 247   Should have been false
FFT inverse scaled size 32, SNR 34.860
FFT size 64
FFT forward unscaled size 64, SNR 27.959
FFT inverse unscaled size 64, SNR 29.148
FFT forward scaled size 64, SNR 6.021
test_fft_c2c_1d_int16_conformance Line 247   Should have been false
FFT inverse scaled size 64, SNR 7.959
test_fft_c2c_1d_int16_conformance Line 266   Should have been false
FFT size 128
FFT forward unscaled size 128, SNR 23.227
FFT inverse unscaled size 128, SNR 28.519
FFT forward scaled size 128, SNR 0.000
test_fft_c2c_1d_int16_conformance Line 247   Should have been false
FFT inverse scaled size 128, SNR 0.000
test_fft_c2c_1d_int16_conformance Line 266   Should have been false
FFT size 256
FFT forward unscaled size 256, SNR -3.522
test_fft_c2c_1d_int16_conformance Line 209   Should have been false
FFT inverse unscaled size 256, SNR -9.542
test_fft_c2c_1d_int16_conformance Line 228   Should have been false
FFT forward scaled size 256, SNR -2.499
test_fft_c2c_1d_int16_conformance Line 247   Should have been false
FFT inverse scaled size 256, SNR -2.499
test_fft_c2c_1d_int16_conformance Line 266   Should have been false
FFT size 512
FFT forward unscaled size 512, SNR -9.542
test_fft_c2c_1d_int16_conformance Line 209   Should have been false
FFT inverse unscaled size 512, SNR -7.044
test_fft_c2c_1d_int16_conformance Line 228   Should have been false
FFT forward scaled size 512, SNR 6.021
test_fft_c2c_1d_int16_conformance Line 247   Should have been false
FFT inverse scaled size 512, SNR 0.000
test_fft_c2c_1d_int16_conformance Line 266   Should have been false
FFT size 1024
FFT forward unscaled size 1024, SNR -18.722
test_fft_c2c_1d_int16_conformance Line 209   Should have been false
FFT inverse unscaled size 1024, SNR 2.499
test_fft_c2c_1d_int16_conformance Line 228   Should have been false
FFT forward scaled size 1024, SNR -6.021
test_fft_c2c_1d_int16_conformance Line 247   Should have been false
FFT inverse scaled size 1024, SNR 0.000
test_fft_c2c_1d_int16_conformance Line 266   Should have been false
FFT size 2048
FFT forward unscaled size 2048, SNR -12.041
test_fft_c2c_1d_int16_conformance Line 209   Should have been false
FFT inverse unscaled size 2048, SNR -21.584
test_fft_c2c_1d_int16_conformance Line 228   Should have been false
FFT forward scaled size 2048, SNR -9.542
test_fft_c2c_1d_int16_conformance Line 247   Should have been false
FFT inverse scaled size 2048, SNR -9.542
test_fft_c2c_1d_int16_conformance Line 266   Should have been false
FFT size 4096
FFT forward unscaled size 4096, SNR -12.279
test_fft_c2c_1d_int16_conformance Line 209   Should have been false
FFT inverse unscaled size 4096, SNR -1.214
test_fft_c2c_1d_int16_conformance Line 228   Should have been false
FFT forward scaled size 4096, SNR -12.041
test_fft_c2c_1d_int16_conformance Line 247   Should have been false
FFT inverse scaled size 4096, SNR -12.041
test_fft_c2c_1d_int16_conformance Line 266   Should have been false
                           1 run  25 failed                           

I have used 

/**
 * @brief  Calculation of SNR
 * @param  ne10_fft_cpx_int16_t*  Pointer to the reference buffer
 * @param  ne10_fft_cpx_int16_t*  Pointer to the test buffer
 * @param  ne10_uint32_t    total number of samples
 * @return ne10_float32_t   SNR, max of real or imaginary
 * The function returns the worst SNR (real or imaginary part) of each individual sample
 * in the test data when compared to the reference data
 */

ne10_float32_t CAL_SNR_CPX16 (ne10_fft_cpx_int16_t *pRef, ne10_fft_cpx_int16_t *pTest, ne10_uint32_t buffSize)
{
      ne10_int32_t EnergySignal, EnergyError;
    ne10_uint32_t i;
    double SNR;
    double minSNR = DBL_MAX;
    double toLog;

    for (i = 0; i < buffSize; i++)
    {
      // promote from int16 to int32 before multiplication below
      ne10_int32_t refR = pRef[i].r;
      ne10_int32_t refI = pRef[i].i;
      ne10_int32_t tstR = pTest[i].r;
      ne10_int32_t tstI = pTest[i].i;
      ne10_int32_t difR = refR-tstR;
      ne10_int32_t difI = refI-tstI;

        // check real part
        EnergySignal = refR * refR; // 32 bit results, overflow should not occur
        EnergyError = difR * difR;

        if(EnergyError > 0)
        {
            toLog = ((double)EnergySignal) / ((double)EnergyError);
            if(toLog > 0.0)
            {
                  SNR = 10.0 * log10 (toLog);

                  if(SNR < minSNR)
                        minSNR = SNR;
            }
        }

        // check imaginary part
        EnergySignal = refI * refI;
        EnergyError = difI * difI;

        if(EnergyError > 0)
        {
            toLog = ((double)EnergySignal) / ((double)EnergyError);
            if(toLog > 0.0)
            {
                  SNR = 10.0 * log10 (toLog);

                  if(SNR < minSNR)
                        minSNR = SNR;
            }
        }

    }

    if (minSNR == DBL_MAX)
      minSNR = 99999; // to save a long printout

    return (ne10_float32_t)minSNR;

}

in place of your                

        snr = CAL_SNR_FLOAT32 (out_c_tmp, out_neon_tmp, (fftSize / 2 + 1) * 2);
        assert_false ( (snr < SNR_THRESHOLD_INT16));

I have

        snr = CAL_SNR_CPX16 ((ne10_fft_cpx_int16_t*)out_c, (ne10_fft_cpx_int16_t*)out_neon, fftSize);
        printf ("FFT forward scaled size %d, SNR %.3f\n", fftSize, snr);
        assert_false ( (snr < SNR_THRESHOLD_INT16));

Here is some more information ...

I have been doing some known answer testing of the 16 bit complex to complex scaled FFT _neon functions in Ne10. 
I am getting some failures, forward and inverse, at sizes 32, 64, 128 512 and 2048, the _c functions in Ne10 give the expected results.

Here is a set of 32 point test data that is failing. This is copied to 64 byte aligned buffers before calling the Ne10 Neon FFT function.

static const ne10_fft_cpx_int16_t input[32] =
{
            { 25908, 13775 }, { 14971, 25956 }, { -6975, -6723 }, { 26468, -12543 }, { -7333, 4625 }, { -9597, 15315 }, { 16079, 15491 }, { 15691, -23638 },
            { -19650, -14903 }, { 11825, 26944 }, { -8661, 1157 }, { -22677, 23653 }, { -19460, 1177 }, { 10147, -4029 }, { 12297, -26842 }, { -23066, -23274 },
            { -30946, -9497 }, { -12633, 12929 }, { -23418, -6891 }, { -28322, 11517 }, { 14741, -19746 }, { 12715, 7583 }, { 10151, 2883 }, { -26326, 2973 },
            { -22557, 23769 }, { -2357, 30800 }, { 14933, 2029 }, { 11791, 12635 }, { -8381, -7299 }, { -26992, 18579 }, { -19701, -26184 }, { -12415, 18644 }
};

static const ne10_fft_cpx_int16_t expected_output[32] =
{
            { -4180, 2840 }, { 1867, 1340 }, { -1774, -4803 }, { 1766, -163 }, { 2392, 1085 }, { -249, -5008 }, { 3475, 4094 }, { 2673, 4352 },
            { 1929, -624 }, { 2263, 3830 }, { 633, -812 }, { 2087, -916 }, { 1224, -1539 }, { -1855, -2455 }, { -1517, -1479 }, { -1857, -2706 },
            { -381, -6163 }, { 709, 2332 }, { 2841, -1450 }, { 3757, -1416 }, { -2553, 3749 }, { 2187, 1652 }, { 4930, 1854 }, { 2218, -3987 },
            { -5828, 2935 }, { -635, -621 }, { 1821, 2086 }, { 8206, 7293 }, { -4414, 1004 }, { 258, 4021 }, { -1117, -636 }, { 5032, 4088 }
};

Actual Output values are

[{-4181, 2838}, {3475,3746},{-1775,-4804},{1200,-3004} 

….  

{-4414,1003},{3098,4585},{-1118,-637},{2624,2478}]

You will see that it is every other output value that looks to be in error.

My platform is Linux an an Altera ArriaVSoc which host an Arm Cortex A9

**Comment by Phillip-Wang** [comment]
@billChadwick Hi, I am looking into this issue. Can you provide more information about your user case. For example, are you using Ne10 in some specific library that requires 16-bits fixed-point FFT? 

Also, I am curious whether it is possible for you to switch to 32-bits fixed-point FFT.

**Comment by billChadwick** [comment]
Phil,

Our use case is embedded signal processing. A 16 bit, fixed point FFT is essential for performance.
I suspect an issue with scaling.

Bill

**Comment by Phillip-Wang** [comment]
@billChadwick Thanks for you information. Can you provide a patch to update our conformance test? Guide can be found in [contributing.md](https://github.com/projectNe10/Ne10/blob/master/contributing.md)

**Comment by billChadwick** [comment]
Phil,

I am not sure I will be able to do that at all quickly as I would need to pursue a CLA through Thales legal which would take a while, then I would need some funding …

Is the fault I reported linked to the Issue  you have just raised here https://github.com/projectNe10/Ne10/issues/101 ?

I think what is important is to use some full amplitude (unit circle) data during testing e.g. 1,0     0,1          0,-1        -1,1         .707,.707              -.707,.707            -.707,-.707           .707,-.707

Bill

**Comment by Phillip-Wang** [comment]
We do have a plan to add test cases you mentioned. Currently, we don't have enough bandwidth for it. You have enough time, since it is not blocking existing users.

I don't think this issue is related to #101.

**Comment by Phillip-Wang** [comment]
Hi @billChadwick ,

I failed to reproduce this issue. Could you provide more detail of your test case? Are you sure the input of ne10_fft_c2c_1d_int16_neon is the expected input?
