### ISSUE TITLE
Contains non position-independent instruction

### ISSUE THREAD

**Issue by h6ah4i** [projectNe10/Ne10#83]
Hi. I noticed that this library contains non position-independent instructions in the hand written assembly code. If shared library is non-PIC, Android warns the below message in logcat.

> libfoo.so has text relocations. This is wasting memory and is a security risk. Please fix.

The culprit is the pseudo LDR instruction which has label in second operand.
- [ARM Compiler armasm User Guide - 10.45 LDR pseudo-instruction](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0473j/dom1361289875065.html)

**Comment by marforic** [comment]
I can confirm this and that the pull request solves the issues.
