### ISSUE TITLE
unequal forward/reverse scaling factors in NE10_fft_float32.neon.c

### ISSUE THREAD

**Issue by hamgravy** [projectNe10/Ne10#90]
There is an issue with NE10_fft_float32.neon.c, particularly with ne10_fft4_backward_float32, ne10_fft8_backward_float32, and possibly others. 

There are "0.25f" and "0.125f" scaling factors in the two respectively mentioned "backward" functions that are not "undone" by the forward transform, which causes scaling issues. 

The issue was discovered when comparing Ne10 fft results with octave and other fft packages. Simply removing the scaling factor fixes the issue.

**Comment by cucurbita** [comment]
@hello Phillip happy new year!, sounds good! for my concern, built-in is preferable to runtime branch checking; anyway if people want two different symbols exported, that could be fixed at build-time, e.g by aliasing, wrapping too different calls into a macro; building the same inlined code twice setting and resetting the local macro.

**Comment by hamgravy** [comment]
@Phillip-Wang, it would be best if it were run-time for me, just like the scaling flag for the fixed-point fft functions.

**Comment by Phillip-Wang** [comment]
@hamgravy, thanks for your feedback. We will have a plan for it.

**Comment by Phillip-Wang** [comment]
@hamgravy, I have updated our API to provide both scaled and unscaled forward/backward FFT. Currently, only non-power-of-2 floating-point complex FFT is affected. I would like to know how it works for you.

**Comment by hamgravy** [comment]
Fantastic. I'll test it out ASAP. Thanks!

**Comment by hamgravy** [comment]
The updates work well for me. I assume scaling selection for the power-of-two transform sizes are next.

**Comment by Phillip-Wang** [comment]
@hamgravy I have opened another issue for power-of-2 FFT.
