### ISSUE TITLE
Can't build for aarch64

### ISSUE THREAD

**Issue by zougloub** [projectNe10/Ne10#94]
I can't figure out how to build for aarch64, I've spent some time already but without success...

**Comment by Phillip-Wang** [comment]
Hi, I assume you are using DSP module. Currently, you have to modify the following files:

1. [CMakeLists.txt](https://github.com/projectNe10/Ne10/blob/master/CMakeLists.txt)
    * Disable all modules but DSP
    * Replace -march=armv7-a by -march=armv8-a
    * Replace ${ANDROID_TOOLCHAIN_PATH}/arm-linux-androideabi-* to their counterparts
2. [CMakeLists.txt](https://github.com/projectNe10/Ne10/blob/master/modules/CMakeLists.txt)
    * Disable all *.neon.c and *.neon.s files
    * Also enable all *.neonintrinsic.c and *.neoninstrinc.cpp files
3. [GNUlinux_config.cmake](https://github.com/projectNe10/Ne10/blob/master/GNUlinux_config.cmake)
    * If your are compiling for linux, change all arm-linux-gnueabihf-* to their counterparts

**Comment by ashi08104** [comment]
Because some part of modules have not been optimized for aarch64, the build system is not enable for aarch64 yet. I'll enable it soon.

**Comment by oscarbg** [comment]
also please support ios arm64 target as next month apps will require arm64 support on ios!

**Comment by oscarbg** [comment]
also please support ios arm64 target as next month apps will require arm64 support on ios!

**Comment by zhongweiy** [comment]
Hi, @zougloub, Aarch64 building for Android is enabled now. Please check.

**Comment by jaydarkdry** [comment]
Hi, I try to build on AArch64 with the CMake on Android.
I use the NDK R10D.

The CMake set up like this:
'Unix Makefiles' -DCMAKE_INSTALL_PREFIX=/home/root/810/prebuilts/Ne10 -DNE10_ENABLE_MATH=0 -DNE10_ENABLE_IMGPROC=0 -DNE10_ENABLE_PHYSICS=0 -DNE10_ANDROID_TARGET_ARCH=armv8 in /home/root/810/buildroot/Ne10
-- The C compiler identification is GNU 4.9.0
-- The CXX compiler identification is GNU 4.9.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/opt/android/android-sysroot-aarch64-linux-androideabi-4.9/bin/aarch64-linux-android-as
-- Check for working C compiler: /home/opt/android/android-sysroot-aarch64-linux-androideabi-4.9/bin/aarch64-linux-android-gcc
-- Check for working C compiler: /home/opt/android/android-sysroot-aarch64-linux-androideabi-4.9/bin/aarch64-linux-android-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/opt/android/android-sysroot-aarch64-linux-androideabi-4.9/bin/aarch64-linux-android-g++
-- Check for working CXX compiler: /home/opt/android/android-sysroot-aarch64-linux-androideabi-4.9/bin/aarch64-linux-android-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Building type: RELEASE
-- Configuring done
-- Generating done

But I get this error:
[  3%] Building C object modules/CMakeFiles/NE10.dir/__/common/NE10_mask_table.c.o
cd /home/root/810/buildroot/Ne10/modules && /home/opt/android/android-sysroot-aarch64-linux-androideabi-4.9/bin/aarch64-linux-android-gcc  -DNE10_ENABLE_DSP -DNE10_ENABLE_HF -O2 -DNDEBUG -mthumb-interwork -mthumb -march=armv7-a -mfpu=vfp3 -I/home/root/810/buildroot/Ne10/inc -I/home/root/810/buildroot/Ne10/common    -o CMakeFiles/NE10.dir/__/common/NE10_mask_table.c.o   -c /home/root/810/buildroot/Ne10/common/NE10_mask_table.c
aarch64-linux-android-gcc: error: unrecognized command line option '-mthumb-interwork'
aarch64-linux-android-gcc: error: unrecognized command line option '-mthumb'
aarch64-linux-android-gcc: error: unrecognized command line option '-mfpu=vfp3'

Thx

**Comment by Phillip-Wang** [comment]
@jaydarkdry ,

[android_config.cmake](https://github.com/projectNe10/Ne10/blob/master/android/android_config.cmake)  only accepts  armv7 or aarch64 as NE10_ANDROID_TARGET_ARCH.
Have you captures error message: "[No NE10_ANDROID_TARGET_ARCH is specified, availiable target architectures are: armv7, aarch64.](https://github.com/projectNe10/Ne10/blob/master/android/android_config.cmake)"

**Comment by jaydarkdry** [comment]
@Phillip-Wang,

I didn't use the android_config.cmake, the main reason is that the step:

cmake .... complain me:CMake Error: The source directory "/home/opt/Ne10/android/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

I run the Cmake on NE10/modules/CmakeLists.txt

**Comment by Phillip-Wang** [comment]
@jaydarkdry,

According to [BuildingNe10.txt](https://github.com/projectNe10/Ne10/blob/master/doc/BuildingNe10.txt):
```shell
cd $NE10PATH
export ANDROID_NDK=/absolute/path/of/android-ndk
mkdir build && cd build
cmake -DCMAKE_TOOLCHAIN_FILE=path/of/android_config.cmake ..
make
```

You build Android demo at $NE10PATH, instead of $NE10PATH/modules.
