### ISSUE TITLE
Trouble compiling on aarch64 with marmalade

### ISSUE THREAD

**Issue by Codewyvern** [projectNe10/Ne10#95]
I want to switch from FFTS to Ne10 because I need to support aarch64 by february (apples requirement).

The problem I am having is I use an sdk called marmalade which uses its own build system (not cmake). So what I normally do is is pick out the files I need and delete the rest and set any defines/cflags. This works for most other libraries but for Ne10 I am getting 581 errors, I dont want to spam them all here but most of them are in NE10_dsp.h.

Error	599	error : storage class specified for parameter 'ne10_fft_alloc_c2c_float32' (col 37)	c:\project\code\ne10\src\inc\NE10_dsp.h	49

I am not sure what is wrong with this at all:
extern ne10_fft_cfg_float32_t (*ne10_fft_alloc_c2c_float32) (ne10_int32_t nfft);
but gcc does not like it.

Also some function pointers like this:
extern void ne10_fir_float_neon (const ne10_fir_instance_f32_t * S,
                                     ne10_float32_t * pSrc,
                                     ne10_float32_t * pDst,
                                     ne10_uint32_t blockSize)
    asm ("ne10_fir_float_neon");

cause errors, I am not even sure where that asm macro is defined or what it does exactly.

I more or less followed instructions on the issue below mine like removing .s and .neon.s/c files and leaving only intrinsic's.

I would very much appreciate some guidance on how to compile this without CMake because right now I am getting nowhere.

Thanks

**Comment by Phillip-Wang** [comment]
Is it the same issue as #76 ?

**Comment by Codewyvern** [comment]
Ahhh yes it very well could be, is there any simple way to remove the asm labels?

**Comment by zhongweiy** [comment]
Is it solved? If I remember correctly, ne10 has not used c99 flag.

**Comment by Codewyvern** [comment]
yep its solved, and I was using c99 flag for my other code, thanks again.

**Comment by zhongweiy** [comment]
Thanks!
