### ISSUE TITLE
Plea for intrinsic FFT versions for ARMv7

### ISSUE THREAD

**Issue by johnridges** [projectNe10/Ne10#96]
I'd like to make a case for also providing intrinsic versions of the FFTs for ARMv7, even if they aren't as fast as the assembly versions. The reason is that the assembly versions would require major changes to pass Google's Native Client validator, while an intrinsic version would always pass (being C). For those of us writing Native Client code, this would be a big help.

**Comment by Phillip-Wang** [comment]
@johnridges Can you provide more details about "major changes"? Have you already finished this "major changes"?

**Comment by johnridges** [comment]
@Phillip-Wang No,I have not written any Native Client assembly code, and I don't really want to (see https://developer.chrome.com/native-client/reference/sandbox_internals/arm-32-bit-sandbox for a description of what you have to go through to do it). I've written some inline assembly, which is valid for Native Client as long as you only work within registers and don't try to load or store to memory). The nice thing about C is that the Native Client compiler will always generate valid code.

If you want an example of someone who *has* written Native Client assembly code, take a look at Google's libyuv project. It looks like something you don't undertake lightly.

**Comment by Phillip-Wang** [comment]
@johnridges Areyou building Ne10 with cmake? Or are you integrating it into you own repo?
For the latter case, you can simply remove all neon.c and neon.s files from you object list. And then include all neonintrinsic.c neonintrinsic.cpp file.
It should work fine for complex fft.

**Comment by johnridges** [comment]
@Phillip-Wang OK, great. I'll try that.

**Comment by Phillip-Wang** [comment]
@johnridges Please let us know if there is any problem.
