### ISSUE TITLE
CMake fails with GNU Linux

### ISSUE THREAD

**Issue by heing** [projectNe10/Ne10#97]
CMake fails with GNULinux:
```
$ cmake -DCMAKE_TOOLCHAIN_FILE=../Ne10/GNUlinux_config.cmake ..
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-linux-gnueabihf-as
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:57 (if):
  if given arguments:

    "STREQUAL" "armv7"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
```

A workaround is to add "-DNE10_ANDROID_TARGET_ARCH=armv7" to cmake command line. I understand this has to do with Android being the primary development platform, but I think the GNU Linux platform support should still be kept. ARM is much more than Android and iOS.

**Comment by Phillip-Wang** [comment]
@heing thanks for you report.

**Comment by zhongweiy** [comment]
@heing we are planing to drop the support for GNU Linux platform. Because most of our users are under Android. So if you could provide some specific use case for GNU Linux, it would help us make right decision. Thanks.

**Comment by zhongweiy** [comment]
Project Opus has reported that they are using NE10 under GNU Linux. This should be a good case. So we will continue supporting GNU Linux. @heing

**Comment by heing** [comment]
Great! Thanks. We use Altera Arria 10 SoC with embedded Linux using Yocto. We generate C code from Matlab which uses the Ne10 library.

**Comment by heing** [comment]
@zhongweiy Latest commit works fine with me.

**Comment by zhongweiy** [comment]
@heing Thanks for your feedback!

**Comment by jeras** [comment]
I am from Red Pitaya, we would like to use Ne10 on Xilinx Zynq and maybe later on ZynqMP (AArch64).
I asked a Debian developer to package this library for us:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837078

I do not have much experience with CMAKE, but is seems Linux [compile instructions](https://github.com/projectNe10/Ne10/blob/master/doc/BuildingNe10.txt) (line 47) are wrong.
Exporting  the NE10_LINUX_TARGET_ARCH variable did not work. I had to define the architecture in command line:
```
cmake -DNE10_LINUX_TARGET_ARCH=armv7 -DGNULINUX_PLATFORM=ON ..
```

**Comment by joesavage** [comment]
@jeras Yeah, I had to do the same. Seems like the build instructions are wrong and should probably be updated.
