### ISSUE TITLE
Question about Ne10

### ISSUE THREAD

**Issue by nafisi** [projectNe10/Ne10#98]
Hello
I gad two questions:
1- can we use ne10 withuout an operationg system
2- what does count mean in this math function:
ne10_mulmat_4x4f_neon (ne10_mat4x4f_t *dst, ne10_mat4x4f_t *src1, ne10_mat4x4f_t *src2, ne10_uint32_t count) 
It has said the number of "The number of items in the input arrays" but I dont understand

**Comment by joesavage** [comment]
If I'm not mistaken, `count` here is the number of matrices that you want to multiply. So if you only want to perform a single matrix multiplication, you can just use `1`. The documentation could definitely be clearer here though, it's not immediately obvious what "number of items" means without taking a closer look at what's going on.
